### ISSUE TITLE
[Page Request] Updating from 1.12 to 1.13

### ISSUE THREAD

**Issue by Aeltumn** [MinecraftForge/Documentation#216]
Because of the major differences between 1.12 and 1.13 I feel it'd be helpful for mod authors if there was a page on the documentation to effectively and concretely explain how to update, with links to utilities to help conversion. (site for lang files to json, maybe scripts for auto-renaming files) At the very least a link to the [1.13 primer](https://gist.github.com/williewillus/353c872bcf1a6ace9921189f6100d09a) could really help those trying to update.

I'd glady write a draft if this is something that would fit in the documentation but I'd like to pitch the idea first and collect some opinions.

**Comment by tterrag1098** [comment]
I've long asked @williewillus to incorporate his primers as part of the docs...

**Comment by williewillus** [comment]
I don't like having updating guides in the docs because at some point they're no longer useful and someone has to remove it.

Stable, version-specific info should be there instead ,which I'm starting to do with my PRs (#213, #214 )

**Comment by daniel-goossens** [comment]
I get that, however I still think the information is very important to provide. Maybe there could be a seperate section specifically called "Updating from legacy versions" where future updates could also be put, as in there's a page called 1.12 -> 1.13 and in the future there would be pages called 1.14 -> 1.15 etc. where the pages are written during the update and afterwards never touched again. In that way they are eventually not useful but their inclusion is clear, they don't have to be removed because they are by definition redundant for new users, future users wouldn't in any way get confused by it and noone would expect it to do more than telling them how to specifically update from one specfic version to another.

**Comment by DarkGuardsman** [comment]
I would also like to see a porting from legacy section. Especially for a page linking to or including guides on porting. As I often forget that there is a primers and have to pester people for links. So a consistent place to find these links would be useful. Not just for myself but other developers in the community. 

This would also be a great place to shove all the content the docs have currently referencing older versions. Specifically the difference between the 1.7 and 1.12 way IFluidHandler works.
