### ISSUE TITLE
Sets are unordered and don't have duplicates

### ISSUE THREAD

**Issue by ivxvm** [MinecraftForge/Documentation#396]
From https://github.com/MinecraftForge/Documentation/blob/1.16.x/docs/blocks/states.md:
> A unique triple can be constructed from the Block, the set of Property<?>, and the set of values for those properties. This unique triple is called a BlockState.

The problem is that sets are unordered and don't have duplicates. Without order you can't maintain the link which property corresponds to which value, without duplicates, moreover, you can even get different number of properties and values because it's perfectly fine for two properties to have the same value. I suggest changing it to `collection` or `sequence` or `array`. For example:

> An unique triple can be constructed from the Block, a collection of Property<?>, and a collection of values for those properties. This unique triple is called a BlockState.

**Comment by ChampionAsh5357** [comment]
Technically, a `BlockState` is constructed based on two concepts: a map which holds the property to value, and a table which references all `BlockState`s that are one step away from the current state (meaning that only a single property has changed its value).  All keys in a map are a set, so it would be a set of properties. Values can also be a set in this context as long as it has some context to the key, hence the 'set of values for those properties' defining the set mapping between the property set and the value set. It's simply a clever wording of a map.

However, if you really wanted to change it, it would be become a unique pair from the block and a map of the properties to their associated values. That would bring it to a more concise definition of a `BlockState` instead of a misinterpretation.

**Comment by ivxvm** [comment]
> Values can also be a set in this context as long as it has some context to the key, hence the 'set of values for those properties' defining the set mapping between the property set and the value set. It's simply a clever wording of a map.

This makes sense, but in context of programming people often expect the word "set" to be representing either the concrete implementation in context of language talked about, or at least abstract data type having certain operations and properties. Going more abstract than abstract data type brings more space for misinterpretations, which is unnecessary when it doesn't take much more words to describe it in more precise terms.

>  unique pair from the block and a map of the properties to their associated values

This is a much better description in my opinion.

**Comment by ChampionAsh5357** [comment]
Fair enough, you're welcome to make a PR for it. I'll get around to this when I begin the 1.18 update.
